### ISSUE TITLE
messagebox example crashes

### ISSUE THREAD

**Issue by rakyll** [veandco/go-sdl2#181]
```
$ go run $GOPATH/src/github.com/veandco/go-sdl2/examples/messagebox/messagebox.go

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x4106500, 0xc82000a330)
	/Users/jbd/go/src/runtime/panic.go:483 +0x3f3
github.com/veandco/go-sdl2/sdl.ShowMessageBox(0xc82004fef0, 0xc82000a300, 0x0, 0x0)
	/Users/jbd/src/github.com/veandco/go-sdl2/sdl/video.go:614 +0x4cc
main.main()
	/Users/jbd/src/github.com/veandco/go-sdl2/examples/messagebox/messagebox.go:37 +0x1ef
exit status 2
```

**Comment by jalan** [comment]
Nice to see some results from 1.6's [new rules for sharing Go pointers with C code](https://tip.golang.org/doc/go1.6#cgo).

Here's another:

```
$ cd $GOPATH/src/github.com/veandco/go-sdl2/sdl_image
$ go test
--- FAIL: TestLoadFormat (0.00s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
        panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 7 [running]:
panic(0x57e960, 0xc82000a6e0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8200241b0)
        /usr/lib/go/src/testing/testing.go:467 +0x192
panic(0x57e960, 0xc82000a6e0)
        /usr/lib/go/src/runtime/panic.go:426 +0x4e9
github.com/veandco/go-sdl2/sdl._cgoCheckPointer0(0x544040, 0x886aa0, 0x0, 0x0, 0x0, 0x48ff0e)
        ??:0 +0x4d
github.com/veandco/go-sdl2/sdl.RWFromMem(0x886aa0, 0x1, 0x5b3e60)
        /home/jason/code/go/src/github.com/veandco/go-sdl2/sdl/rwops.go:70 +0x5d
github.com/veandco/go-sdl2/sdl_image.TestLoadFormat(0xc8200241b0)
        /home/jason/code/go/src/github.com/veandco/go-sdl2/sdl_image/sdl_image_test.go:267 +0x6bc
testing.tRunner(0xc8200241b0, 0x88a950)
        /usr/lib/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /usr/lib/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL    github.com/veandco/go-sdl2/sdl_image    0.005s

**Comment by aqiank** [comment]
@rakyll, I have the fix merged into master.

@jalan, good find! I'll create another issue for that one.
