### ISSUE TITLE
sdl_image: TestLoadFormat fails test

### ISSUE THREAD

**Issue by aqiank** [veandco/go-sdl2#183]
```
--- FAIL: TestLoadFormat (0.00s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
        panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 7 [running]:
panic(0x8180880, 0x1840a230)
        /home/jacky/Downloads/go/src/runtime/panic.go:464 +0x326
testing.tRunner.func1(0x18412240)
        /home/jacky/Downloads/go/src/testing/testing.go:467 +0x14f
panic(0x8180880, 0x1840a230)
        /home/jacky/Downloads/go/src/runtime/panic.go:426 +0x3fd
github.com/veandco/go-sdl2/sdl._cgoCheckPointer0(0x815cb60, 0x824ce80, 0x0, 0x0, 0x0, 0x80c2c4a)
        ??:0 +0x41
github.com/veandco/go-sdl2/sdl.RWFromMem(0x824ce80, 0x1, 0x819bb34)
        /home/jacky/src/github.com/veandco/go-sdl2/sdl/rwops.go:70 +0x54
github.com/veandco/go-sdl2/sdl_image.TestLoadFormat(0x18412240)
        /home/jacky/src/github.com/veandco/go-sdl2/sdl_image/sdl_image_test.go:267 +0x586
testing.tRunner(0x18412240, 0x824ed98)
        /home/jacky/Downloads/go/src/testing/testing.go:473 +0x8f
created by testing.RunTests
        /home/jacky/Downloads/go/src/testing/testing.go:582 +0x6f2
exit status 2
FAIL    github.com/veandco/go-sdl2/sdl_image    0.021s
```

**Comment by aqiank** [comment]
Fixed
