### ISSUE TITLE
sdl.AddEventWatch broken in go 1.6

### ISSUE THREAD

**Issue by gerow** [veandco/go-sdl2#194]
I'm still not sure if this is 1.6-specific or just something that's broken for other reasons. Looking into solutions, though. Anyway, the below commands should make the situation clear:

```
gerow@mgair:~/go/src/github.com/veandco/go-sdl2/sdl$ go version
go version go1.6 darwin/amd64
gerow@mgair:~/go/src/github.com/veandco/go-sdl2/sdl$ go test
--- FAIL: TestEventsFilterEventsFuncQ (0.29s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
	panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 18 [running]:
panic(0x4195340, 0xc82000a790)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc82008e630)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x4195340, 0xc82000a790)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/veandco/go-sdl2/sdl._cgoCheckPointer0(0x4153c40, 0xc82000a780, 0x0, 0x0, 0x0, 0xc82008e630)
	??:0 +0x4d
github.com/veandco/go-sdl2/sdl.FilterEvents(0x5a14500, 0xc82000a770)
	/Users/gerow/go/src/github.com/veandco/go-sdl2/sdl/events.go:644 +0x7b
github.com/veandco/go-sdl2/sdl.FilterEventsFunc(0xc82000a770)
	/Users/gerow/go/src/github.com/veandco/go-sdl2/sdl/events.go:648 +0x48
github.com/veandco/go-sdl2/sdl.TestEventsFilterEventsFuncQ(0xc82008e630)
	/Users/gerow/go/src/github.com/veandco/go-sdl2/sdl/events_test.go:166 +0x2c3
testing.tRunner(0xc82008e630, 0x42c4e48)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL	github.com/veandco/go-sdl2/sdl	1.851s
```

**Comment by veeableful** [comment]
Fixed by #195
