### ISSUE TITLE
Crash on surface.FillRect()

### ISSUE THREAD

**Issue by handicraftsman** [veandco/go-sdl2#201]
Line:
    `gfxSurf.FillRect(&gfxLeftPanel, 0xffff0000)`
Crash:
````
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 6 [running]:
panic(0x812d060, 0x1846a008)
	/usr/lib/go/src/runtime/panic.go:481 +0x326
github.com/veandco/go-sdl2/sdl.(*Surface).FillRect(0x81d1f60, 0x81e1d20, 0xffff0000, 0x0, 0x0)
	/home/ancient/load/go/src/github.com/veandco/go-sdl2/sdl/surface.go:247 +0x4e
main.gfxMain()
	/home/ancient/code/grgl/gfx.main.go:41 +0x30a
created by main.main
	/home/ancient/code/grgl/main.go:14 +0xc8

````

**Comment by veeableful** [comment]
Hi @handicraftsman, could you give me a minimal code that could reproduce the problem? I've tried a simple code that does Surface.FillRect() but it doesn't seem to happen.

**Comment by handicraftsman** [comment]
Okay. (OS - ArchLinux (manjaro) with Go from original repo)
````go
//main.go
package main

/** Imports **/
import "fmt"

/** Config Vars **/
var sName = "grgl"
var sVer = "Dev"

/** The Center of the Universe (main func) **/
func main() {
	fmt.Println("# Main thread is started") // Self-describing

	go gfxMain() // Run graphic thread

	<-cExit                                 // Exit when there's 'true' in 'cExit' channel
	fmt.Println("# Main thread is exiting") // Self-describing
}
````
````go
//chan.go
package main

var cExit = make(chan bool, 1) // Send true there to exit
````
````go
//gfx.main.go
package main

/** Imports **/
import (
	"fmt"
	"log"

	"github.com/veandco/go-sdl2/sdl"
)

/** Variables **/
var gfxWin sdl.Window   // GFX: Window
var gfxWinX = 800       // GFX: WinWidth
var gfxWinY = 480       // GFX: WinHeight
var gfxSurf sdl.Surface // GFX: Surface

var gfxLeftPanel sdl.Rect // GFX: Left Panel

/** Functions **/
func gfxMain() { // GFX: Main
	fmt.Println("# GFX thread is started") // Self-describing, sir!
	sdl.Init(sdl.INIT_EVERYTHING)          // Init SDL

	/** Window Part **/
	gfxWin, err := sdl.CreateWindow((sName + " v" + sVer),
		sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
		gfxWinX, gfxWinY, sdl.WINDOW_SHOWN) // Initialize our window
	if err != nil { // error-handle
		log.Fatal(err)
	}

	gfxLeftPanel = sdl.Rect{
		X: 0,
		Y: 0,
		H: 200,
		W: int32(gfxWinY),
	}

	for {
		fmt.Println("Hi?")
		gfxSurf.FillRect(&gfxLeftPanel, 0xffff0000)
		gfxWin.UpdateSurface()
	}

}

func gfxExit() {
	gfxWin.Destroy()                       // Kill our window
	fmt.Println("# GFX thread is exiting") // Self-describing
	cExit <- true                          // Exit. Just now. Get this channel for only $999.99!
}
````

**Comment by handicraftsman** [comment]
P. S. I am developing roguelike.

**Comment by handicraftsman** [comment]
Updated go-sdl package - still crashes, same error.

**Comment by handicraftsman** [comment]
Full log:
````log
[ancient@NickolayPC grgl]$ make br
go build -o exec
./exec	
# Main thread is started
# GFX thread is started
Hi?
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 6 [running]:
panic(0x812d060, 0x1840a138)
	/usr/lib/go/src/runtime/panic.go:481 +0x326
github.com/veandco/go-sdl2/sdl.(*Surface).FillRect(0x81d1f60, 0x81e1d20, 0xffff0000, 0x0, 0x0)
	/home/ancient/load/go/src/github.com/veandco/go-sdl2/sdl/surface.go:247 +0x4e
main.gfxMain()
	/home/ancient/code/grgl/gfx.main.go:41 +0x30a
created by main.main
	/home/ancient/code/grgl/main.go:14 +0xc8
make: *** [Makefile:7: br] Error 2

````

**Comment by veeableful** [comment]
Oh it seems like you didn't get the surface from the window using Window.GetSurface() or create it using sdl.CreateRGBSurface(). Try doing something like:
```
var gfxSurf *sdl.Surface
gfxSurf, err = gfxWin.GetSurface()
// check error if any
gfxSurf.FillRect(&gfxLeftPanel, 0xffff0000)
gfxWin.UpdateSurface()
```

**Comment by handicraftsman** [comment]
Okay, i'll try (stops PHP dev servers)

**Comment by handicraftsman** [comment]
Thanks. It works.
